#MUST DEFINE:
#COMPILER
#LINKER
#INCLUDE_SWITCH
#DEFINE_SWITCH
#IMPLIB_SWITCH
#DEF_FILE_SWITCH
#LINK_OUTPUT_SWITCH
#IMPLIB_EXT
#OBJ_FILES
#COMPILE_LIBRARY_RELEASE
#COMPILE_LIBRARY_DEBUG
#COMPILE_EXE_RELEASE
#COMPILE_EXE_DEBUG
#LINK_LIBRARY_RELEASE
#LINK_LIBRARY_DEBUG
#LINK_EXE_RELEASE
#LINK_EXE_DEBUG
#LINK_LIBRARIES
#VERSION_SWITCH
import os
#DEFAULT COMPILERS AND SWITCHES#
COMPILER="cl"
CROSS_COMPILER="cl"
LINK_OUTPUT_SWITCH="/out:"
EXE_OUTPUT_SWITCH="/Fe"
DEFINE_SWITCH="/D"
INCLUDE_SWITCH="/I"
VERSION_SWITCH=""
DEF_FILE_SWITCH="/def:"
IMPLIB_SWITCH="/implib:"
IMPLIB_EXT=".lib"
LINKER="link"
CROSS_LINKER="link"
#OBJ FILES#
OBJ_FILES="*.obj"
#STANDARD BUILD OPTIONS
ALL_BUILD="/c /D_WINDOWS /W3 /Zm1000 /TC /fp:precise /D_CRT_SECURE_NO_WARNINGS"
COMPILE_LIBRARY_RELEASE=ALL_BUILD+" /MD /O2 /Ob2 /D NDEBUG"
COMPILE_LIBTRARY_DEBUG=ALL_BUILD+" /D_ROUT /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1"
COMPILE_EXE_RELEASE=COMPILE_LIBRARY_RELEASE
COMPILE_EXE_DEBUG=COMPILE_LIBRARY_DEBUG
LINK_LIBRARY_RELEASE="/DLL  /INCREMENTAL:NO"
LINK_LIBRARY_DEBUG="/DLL /debug /INCREMENTAL"
LINK_EXE_RELEASE="/INCREMENTAL:NO"
LINK_EXE_DEBUG="/debug /INCREMENTAL"
LINK_LIBRARIES='kernel32.lib  user32.lib  gdi32.lib  winspool.lib  shell32.lib  ole32.lib  oleaut32.lib  uuid.lib  comdlg32.lib  advapi32.lib'






