/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TrLib */

#ifndef _Included_TrLib
#define _Included_TrLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TrLib
 * Method:    GetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TrLib_GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     TrLib
 * Method:    InitLibrary
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_TrLib_InitLibrary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     TrLib
 * Method:    GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TrLib_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     TrLib
 * Method:    TerminateLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TrLib_TerminateLibrary
  (JNIEnv *, jclass);

/*
 * Class:     TrLib
 * Method:    TerminateThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TrLib_TerminateThread
  (JNIEnv *, jclass);

/*
 * Class:     TrLib
 * Method:    AllowUnsafeTransformations
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TrLib_AllowUnsafeTransformations
  (JNIEnv *, jclass);

/*
 * Class:     TrLib
 * Method:    ForbidUnsafeTransformations
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TrLib_ForbidUnsafeTransformations
  (JNIEnv *, jclass);

/*
 * Class:     TrLib
 * Method:    Tropen
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_TrLib_Tropen
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     TrLib
 * Method:    Trclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_TrLib_Trclose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     TrLib
 * Method:    Transform
 * Signature: (J[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_TrLib_Transform
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
